name: CI
on: [push]
jobs:
  test:
    name: Test on ${{ matrix.os }} / ${{ matrix.flutter }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./sqflite_support
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        flutter: [stable]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.flutter }}
      - run: dart --version
      - run: flutter --version
      - run: flutter upgrade
      - run: flutter pub get
      - run: flutter test --coverage
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v2
          
  # build_qa_apk:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: dart-lang/setup-dart@v1.3
  #       with: 
  #         SDK: "2.18.0"

  #     - uses: actions/setup-java@v1
  #       with:
  #         java-version: "12.x"

  #     - uses: subosito/flutter-action@v1
  #       with:
  #         flutter-version: "2.8.0"

  #     - run: flutter pub get
  #       working-directory: example

  #     - run: flutter build apk
  #       working-directory: example

  #     - name: Archive APK
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: QA APK
  #         path: example/build/app/outputs/flutter-apk/app-release.apk
  #         retention-days: 2

