name: CI
on: [push]
jobs:
  test_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.0.6"

      - run: flutter pub get

      - run: flutter test --coverage

      - uses: codecov/codecov-action@v1
        with:
          files: ./coverage/lcov.info

      - run: flutter build apk
        working-directory: example
